Week 6/W6D5/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

Week 6/W6D5/ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    validates :birth_date, :color, :name, :sex, :description, presence: true

    def age
        time_ago_in_words(birth_date)
    end

    has_many :requests,
        foreign_key: :cat_id,
        class_name: :Cat_rental_request,
        dependent: :destroy

end

Week 6/W6D5/ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("pending"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CatRentalRequest < ApplicationRecord 
    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: { in: %w(pending approved denied) }

    belongs_to :cat,
        foreign_key: :cat_id,
        class_name: :cat 

    def overlapping_requests
        CatRentalRequest
            .select(**)
            .where(r1.cat = r2.cat)
            .where(r2.start_date < r1.end_date or r2.end_date > r1.start_date )
    end

    # r1 = 2020/4/10 - 2020/4/15
    # r2 = 2020/4/14 - 2020/4/18 OR  #r2.start_date < r1.end_date
    #   2020/4/6 - 2020/4/11 OR  # r2.end_date > r1.start_date
    #   2020/4/11 - 2020/4/13 # combinator


    # CatRentalRequest.all.select do |request|
        cat_id == request.cat_id && date_range

end

Week 6/W6D5/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        # debugger
        @cat = Cat.find(params[:id])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render @cat.errors.full_messages, status: 422
        end
    end

    def create
        @cat = Cat.new(cat_params)

        if @cat.save
            redirect_to cat_url(@cat)
        else
            render @cat.errors.full_messages, status: 422
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
    end
end

Week 6/W6D5/ninety_nine_cats/app/views/cats/_form.html.erb
<% if action == :new %>
<% action_url = cats_url %>
<% else %>
<% action_url = cat_url(cat) %>
<% end %>


<form action="<%=action_url%>" method="post">
    <% if action == :edit %>
        <input type='hidden' name='_method' value= 'patch' >
    <% end %>

    <label for='cat_name'>Name</label>
    <input id='cat_name' type='text' name='cat[name]' value= '<%=cat.name %>'>
    
    <br>
    <label for='cat_birth_date'>Birthdate</label>
    <input id='cat_birth_date' type='date' name='cat[birth_date]' value= '<%=cat.birth_date %>'>

    <br>
    <label for='cat_color'>Color</label>
    <input id='cat_color' type='text' name='cat[color]' value= '<%=cat.color %>'>

    <br>
    <label>Sex</label>
    <label for='cat_sex_male'>Male</label>
    <input id='cat_sex_male' type='radio' name='cat[sex]' value= 'M' <%=cat.sex == 'M' ? "checked" : ""  %>>
    <label for='cat_sex_female'>Female</label>
    <input id='cat_sex_female' type='radio' name='cat[sex]' value= 'F' <%=cat.sex == 'F' ? "checked" : ""  %>>

    <br>
    <label> Description
    <textarea name='cat[description]' <%=@cat.description%>> </textarea>
    </label>

    <br>
    <input type='submit' value='<%= action == :new ? 'Create Cat' : 'Update Cat' %>'>

</form>

Week 6/W6D5/ninety_nine_cats/app/views/cats/edit.html.erb
<h1> Time to edit your cat!! </h1>

<%= render 'form', cat: @cat, action: :edit %>

Week 6/W6D5/ninety_nine_cats/app/views/cats/index.html.erb
<h1>All of the cats in the world!</h1>

<ul>
    <% @cats.each do |cat| %>
    <li><a href ='<%= cat_url(cat) %>'><%= cat.name %></a></li>
    <% end %>
</ul>

Week 6/W6D5/ninety_nine_cats/app/views/cats/new.html.erb
<h1> Time to make a new cat!! </h1>

<%= render 'form', cat: @cat, action: :new %>

Week 6/W6D5/ninety_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
    <thead>
        <tr>
            <th>Attribute</th>
            <th>Value</th>

        </tr>
    </thead>

    <tbody>

        <tr>
            <td>Age</td>
            <td><%= @cat.age %></td>
        </tr>
            
        <tr>
            <td>Birthdate</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>

        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
    
    </tbody>
</table>

Week 6/W6D5/ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>