Week 8/W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :show, :create, :destroy] do
    resources :posts, only: [:update, :edit]
  end
  
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Week 8/W8D1/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  author_id   :integer          not null
#
class Sub < ApplicationRecord
    validates :description, :author_id, presence: true
    validates :title, presence: true, uniqueness: true

    belongs_to :moderator,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User
    
    has_many :postsubs,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :PostSub
    
    has_many :posts,
        through: :postsubs,
        source: :post
end

Week 8/W8D1/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

    before_action :is_moderator?, only: [:update, :edit]

    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find_by(id: params[:id])
        render :show
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = current_user.subs.new(sub_params)
        
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def update
        @sub = Sub.find_by(id: params[:id])

        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    def edit
        @sub = Sub.find_by(id: params[:id])
        render :edit
    end

    private

    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

Week 8/W8D1/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

Week 8/W8D1/reddit_clone/app/views/subs/index.html.erb
<h1>All The Subs</h1>
<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <% end %>
</ul>

<h1>Create a Sub</h1>
<form action='<%= subs_url %>' method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label> Name
        <input type="text" name="sub[title]">
    </label>
    <label> Description
        <input type="text" name="sub[description]">
    </label>
    <button>Submit!</button>
</form>

Week 8/W8D1/reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h3>Description</h3>

<%= @sub.description %>

<a href="<%= new_post_url %>">Make new post!</a>

<a href="<%= edit_sub_url(@sub) %>">Edit!</a>