Week 8/W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :show, :create, :destroy] do
    resources :posts, only: [:update, :edit]
  end
  
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Week 8/W8D1/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true 

    belongs_to :author,
        primary_key: :id,
        foreign_key: :author_id,
        class_name: :User

    has_many :postsubs,
        primary_key: :id,
        foreign_key: :post_id,
        class_name: :PostSub

    has_many :subs,
        through: :postsubs,
        source: :sub,
        dependent: destroy,
        inverse_of: :post
    
    

        #has many subs through association, 2 record active methods, 1) extract ids, subs_id, 2)setter, subs_ids=

end

Week 8/W8D1/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :is_author?, only: [:edit, :update]

    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = current_user.posts.new(post_params) #shouldn't be create, because we're doing @post.save
        #association prefills accessing certain user, moderator_id with current user's id

        if @post.save
            redirect_to post_url(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def update
        @post = Post.find_by(id: params[:id])

        if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash[:errors] = ['Post cannot be edited']
            render :edit
        end
    end

    def edit
        @post = Post.find_by(id: params[:id])
        render :edit
    end

    def destroy
        @post = Post.find_by(id: params[:id])

        if @post.destroy
            redirect_to subs_url
        else
            flash[:errors] = ['Post cannot be destroyed']
            redirect_to post_url(@post)
        end
    end

    private

    def post_params
        params.require(:post).permit(:title, :content, :url, sub_ids: [])
    end


end

Week 8/W8D1/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

Week 8/W8D1/reddit_clone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action='<%= posts_url %>' method='POST'>
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="post[sub_ids][]" value="">

<label>Title:
<input type="text" name="post[title]" value="<%= @post.title %>">
</label>

<label>URL:
<input type="text" name="post[url]" value="<%= @post.url %>">
</label>

<label>Content:
<input type="text" name="post[content]" value="<%= @post.content %>">
</label>

<% Sub.all.each do |sub| %>
   <label>
     <input type='checkbox' name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %>> 
     <%= sub.title %>
   </label>
   <br>
<% end %>
    <button>Edit Post</button>


</form>

Week 8/W8D1/reddit_clone/app/views/posts/new.html.erb
<form action='<%= posts_url %>' method='POST'>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<span>Posts</span>

<% Post.all.each do |post| %>
   <label>
     <input type='checkbox'>
     <%= post.title %>
   </label>
   <br>
<% end %>

<button>Create Post</button>

</form>